### ISSUE TITLE
Introduce API versioning system

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e-api#144] opened 2023-03-18 18:35 UTC
Currently, the API cannot be versioned. Any substantial changes to existing data or responses would be a regression affecting consumers of the API.

Ideally, we would want to introduce something that provides versioned API responses using a format like `/v2/monsters/` so we can make breaking changes when needed.

The number of versions _should_ stay small and such changes should be rare, so this doesn't need to be easy to set up.

A decision would need to be made about what the versionless API endpoint would be: should it stay as v1, or should it transition to being the evergreen "current" version? If the latter, how do we notify consumers in advance of the change?

**Comment by Gredelston** [comment] 2023-03-18 18:47
dupe of #145

**Closed** 2023-03-18 18:46 UTC
